config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :survey_instances
  resources :gamble_results
  
  resources :gambles do
    member do
      get 'run'
      
    end
  end
  
  resources :surveys

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signin'  => 'users#new'
  get 'gamble'  => 'static_pages#gamble'
  get 'vas'     => 'static_pages#vas'
  

  
  

end

app/models/gamble.rb
class Gamble < ActiveRecord::Base
  belongs_to :section
  has_many :gamble_results
  
end

app/controllers/gambles_controller.rb
class GamblesController < ApplicationController
  before_action :set_gamble, only: [:show, :edit, :update, :destroy, :run]

  # GET /gambles
  # GET /gambles.json
  def index
    @gambles = Gamble.all
  end

  # GET /gambles/1
  # GET /gambles/1.json
  def show
  end

  def run
  end

  # GET /gambles/new
  def new
    @gamble = Gamble.new
  end

  # GET /gambles/1/edit
  def edit
  end

  # POST /gambles
  # POST /gambles.json
  def create
    @gamble = Gamble.new(gamble_params)

    respond_to do |format|
      if @gamble.save
        format.html { redirect_to @gamble, notice: 'Gamble was successfully created.' }
        format.json { render :show, status: :created, location: @gamble }
      else
        format.html { render :new }
        format.json { render json: @gamble.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gambles/1
  # PATCH/PUT /gambles/1.json
  def update
    respond_to do |format|
      if @gamble.update(gamble_params)
        format.html { redirect_to @gamble, notice: 'Gamble was successfully updated.' }
        format.json { render :show, status: :ok, location: @gamble }
      else
        format.html { render :edit }
        format.json { render json: @gamble.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gambles/1
  # DELETE /gambles/1.json
  def destroy
    @gamble.destroy
    respond_to do |format|
      format.html { redirect_to gambles_url, notice: 'Gamble was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gamble
      @gamble = Gamble.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gamble_params
      params.require(:gamble).permit(:title, :description, :instructions, :interval, :good_outcome, :bad_outcome)
    end
end

app/helpers/gambles_helper.rb
module GamblesHelper
end

app/views/gambles/_form.html.erb
<%= form_for(@gamble) do |f| %>
  <% if @gamble.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gamble.errors.count, "error") %> prohibited this gamble from being saved:</h2>

      <ul>
      <% @gamble.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %>
  </div>
  <div class="field">
    <%= f.label :interval %><br>
    <%= f.text_field :interval %>
  </div>
  <div class="field">
    <%= f.label :good_outcome %><br>
    <%= f.text_field :good_outcome %>
  </div>
  <div class="field">
    <%= f.label :bad_outcome %><br>
    <%= f.text_field :bad_outcome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gambles/_run.html.erb
<div id="gambleModule" class="container">
  <h1><%= gamble.title %></h1>
  <h2><%= gamble.description %></h2>
  <p><%= gamble.instructions %></p>
  
  <div id="gambleActive">
    <div class="card-group">
      <div id="gambleContinue"class="card">
        <div class="card-block">
          <h4 class="card-title"><%= gamble.good_outcome %></h4>
        </div>
      </div>
      <div id="gambleTakeRisk" class="card">
        <div class="card-block">
          <h4 class="card-title"><%= gamble.bad_outcome %></h4>
          <h5 class="card-text">
            <span id="successPercent"></span>%
            chance of successful outcome.
          </h5>
          <h5 class="card-text">
            <span id="poorPercent"></span>%
            chance of poor outcome.
          </h5>
        </div>
      </div>
    </div>
  </div>
  
  <div id="gambleComplete">
    <h1>All Done. Thanks!</h1>
    <h2>Iterations:
      <span id="gambleIterations"></span>
    </h2>
    <h2>Last-card percentages: <br>
      Success: <span id="gambleSuccessPercent"></span><br>
      Poor: <span id="gamblePoorPercent"></span><br>
    </h2>
    <h2>Card-before-last percentages: <br>
      Interation #: <span id="gambleIterationPrev"></span><br>  
      Success: <span id="gambleSuccessPercentPrev"></span><br>
      Poor: <span id="gamblePoorPercentPrev"></span><br>
    </h2>
  </div>
</div>


<script>
  $("#gambleComplete" ).hide();
  
  var successPercent = [100, 0, 95, 5, 90, 10, 85, 15, 80, 20, 75, 25, 70, 30, 65, 35, 60, 40, 55, 45, 50];
  var poorPercent = [0, 100, 5, 95, 10, 90, 15, 85, 20, 80, 25, 75, 30, 70, 35, 65, 40, 60, 45, 55, 50];
  var gambleIndex = 0
  
  function setSuccessPercent(successPercent){
    $("#successPercent").html(successPercent);  
  }
  function setPoorPercent(poorPercent){
    $("#poorPercent").html(poorPercent);  
  }
  function isGambleOver(gambleIndex, userClick){
    return (userClick === "gambleContinue" && gambleIndex%2 == 0) || (userClick === "gambleTakeRisk" && gambleIndex%2 != 0)
  }
  function computeGambleScore(successPercent, poorPercent, successPercentPrev, poorPercentPrev){
    $("#gambleSuccessPercent").html(successPercent);
    $("#gamblePoorPercent").html(poorPercent);
    $("#gambleSuccessPercentPrev").html(successPercentPrev);
    $("#gamblePoorPercentPrev").html(poorPercentPrev);
  }
  
  function saveGambleResult(successPercent){
    var params = {
      final_good_outcome_percent: successPercent,
      gamble_id: <%= gamble.id %>,
      gamble_result: successPercent
    }
    
    $.post("/gamble_results.json", params, function(data){
        console.log('successfully saved', data);
      })
  }
  
  $("document").ready(function(){
    
    setSuccessPercent(successPercent[gambleIndex]);
    setPoorPercent(poorPercent[gambleIndex]);
    
    $( "#gambleContinue" ).click(function(arg1) {
      console.log( arg1 );
      if (isGambleOver(gambleIndex, "gambleContinue")){
        console.log("It's over");
        $("#gambleActive").hide();
        $("#gambleComplete").show();
        computeGambleScore(successPercent[gambleIndex], poorPercent[gambleIndex], successPercent[gambleIndex-1], poorPercent[gambleIndex-1]);
        $("#gambleIterations").html(gambleIndex);
        $("#gambleIterationPrev").html(gambleIndex-1);
        saveGambleResult(successPercent[gambleIndex]);
      }
      
      gambleIndex ++;
      
      setSuccessPercent(successPercent[gambleIndex]);
      setPoorPercent(poorPercent[gambleIndex]);
    });
    
    $( "#gambleTakeRisk" ).click(function(arg1) {
      console.log( arg1 );
      if (isGambleOver(gambleIndex, "gambleTakeRisk")){
        console.log("it's over");
        $("#gambleActive" ).hide();
        $("#gambleComplete" ).show();
        computeGambleScore(successPercent[gambleIndex], poorPercent[gambleIndex], successPercent[gambleIndex-1], poorPercent[gambleIndex-1]);
        $("#gambleIterations").html(gambleIndex);
        $("#gambleIterationPrev").html(gambleIndex-1);
        saveGambleResult(successPercent[gambleIndex]);
      }
      
      gambleIndex ++;
      
      setSuccessPercent(successPercent[gambleIndex]);
      setPoorPercent(poorPercent[gambleIndex]);
    });
  })
</script>

app/views/gambles/_run_gamble.html.erb
<div id="gambleModule" class="container">
  <h1><%= gamble.title %></h1>
  <h2><%= gamble.description %></h2>
  <p><%= gamble.instructions %></p>
  
  <div id="gambleActive">
    <div class="card-group">
      <div id="gambleContinue"class="card">
        <div class="card-block">
          <h4 class="card-title"><%= gamble.good_outcome %></h4>
        </div>
      </div>
      <div id="gambleTakeRisk" class="card">
        <div class="card-block">
          <h4 class="card-title"><%= gamble.bad_outcome %></h4>
          <h5 class="card-text">
            <span id="successPercent"></span>%
            chance of successful outcome.
          </h5>
          <h5 class="card-text">
            <span id="poorPercent"></span>%
            chance of poor outcome.
          </h5>
        </div>
      </div>
    </div>
  </div>
  
  <div id="gambleComplete">
    <h1>All Done. Thanks!</h1>
    <h2>Iterations:
      <span id="gambleIterations"></span>
    </h2>
    <h2>Last-card percentages: <br>
      Success: <span id="gambleSuccessPercent"></span><br>
      Poor: <span id="gamblePoorPercent"></span><br>
    </h2>
    <h2>Card-before-last percentages: <br>
      Interation #: <span id="gambleIterationPrev"></span><br>  
      Success: <span id="gambleSuccessPercentPrev"></span><br>
      Poor: <span id="gamblePoorPercentPrev"></span><br>
    </h2>
  </div>
</div>


<script>
  $("#gambleComplete" ).hide();
  
  var successPercent = [100, 0, 95, 5, 90, 10, 85, 15, 80, 20, 75, 25, 70, 30, 65, 35, 60, 40, 55, 45, 50];
  var poorPercent = [0, 100, 5, 95, 10, 90, 15, 85, 20, 80, 25, 75, 30, 70, 35, 65, 40, 60, 45, 55, 50];
  var gambleIndex = 0
  
  function setSuccessPercent(successPercent){
    $("#successPercent").html(successPercent);  
  }
  function setPoorPercent(poorPercent){
    $("#poorPercent").html(poorPercent);  
  }
  function isGambleOver(gambleIndex, userClick){
    return (userClick === "gambleContinue" && gambleIndex%2 == 0) || (userClick === "gambleTakeRisk" && gambleIndex%2 != 0)
  }
  function computeGambleScore(successPercent, poorPercent, successPercentPrev, poorPercentPrev){
    $("#gambleSuccessPercent").html(successPercent);
    $("#gamblePoorPercent").html(poorPercent);
    $("#gambleSuccessPercentPrev").html(successPercentPrev);
    $("#gamblePoorPercentPrev").html(poorPercentPrev);
  }
  
  function saveGambleResult(successPercent){
    var params = {
      final_good_outcome_percent: successPercent,
      gamble_id: <%= gamble.id %>,
      survey_instance_id: <%= @survey_instance.id %>
    }
    console.log('saving with params', params)
    $.post("/gamble_results.json", params, function(data){
        console.log('successfully saved', data);
      })
  }
  
  $("document").ready(function(){
    
    setSuccessPercent(successPercent[gambleIndex]);
    setPoorPercent(poorPercent[gambleIndex]);
    
    $( "#gambleContinue" ).click(function(arg1) {
      console.log( arg1 );
      if (isGambleOver(gambleIndex, "gambleContinue")){
        console.log("It's over");
        $("#gambleActive").hide();
        $("#gambleComplete").show();
        computeGambleScore(successPercent[gambleIndex], poorPercent[gambleIndex], successPercent[gambleIndex-1], poorPercent[gambleIndex-1]);
        $("#gambleIterations").html(gambleIndex);
        $("#gambleIterationPrev").html(gambleIndex-1);
        saveGambleResult(successPercent[gambleIndex]);
      }
      
      gambleIndex ++;
      
      setSuccessPercent(successPercent[gambleIndex]);
      setPoorPercent(poorPercent[gambleIndex]);
    });
    
    $( "#gambleTakeRisk" ).click(function(arg1) {
      console.log( arg1 );
      if (isGambleOver(gambleIndex, "gambleTakeRisk")){
        console.log("it's over");
        $("#gambleActive" ).hide();
        $("#gambleComplete" ).show();
        computeGambleScore(successPercent[gambleIndex], poorPercent[gambleIndex], successPercent[gambleIndex-1], poorPercent[gambleIndex-1]);
        $("#gambleIterations").html(gambleIndex);
        $("#gambleIterationPrev").html(gambleIndex-1);
        saveGambleResult(successPercent[gambleIndex]);
      }
      
      gambleIndex ++;
      
      setSuccessPercent(successPercent[gambleIndex]);
      setPoorPercent(poorPercent[gambleIndex]);
    });
  })
</script>

app/views/gambles/edit.html.erb
<h1>Editing Gamble</h1>

<%= render 'form' %>

<%= link_to 'Show', @gamble %> |
<%= link_to 'Back', gambles_path %>

app/views/gambles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gambles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Instructions</th>
      <th>Interval</th>
      <th>Good outcome</th>
      <th>Bad outcome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gambles.each do |gamble| %>
      <tr>
        <td><%= gamble.title %></td>
        <td><%= gamble.description %></td>
        <td><%= gamble.instructions %></td>
        <td><%= gamble.interval %></td>
        <td><%= gamble.good_outcome %></td>
        <td><%= gamble.bad_outcome %></td>
        <td><%= link_to 'Show', gamble %></td>
        <td><%= link_to 'Edit', edit_gamble_path(gamble) %></td>
        <td><%= link_to 'Destroy', gamble, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gamble', new_gamble_path %>

app/views/gambles/new.html.erb
<h1>New Gamble</h1>

<%= render 'form' %>

<%= link_to 'Back', gambles_path %>

app/views/gambles/run_gamble.html.erb
<%= render 'run_gamble', gamble: @gamble %>

app/views/gambles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @gamble.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @gamble.description %>
</p>

<p>
  <strong>Instructions:</strong>
  <%= @gamble.instructions %>
</p>

<p>
  <strong>Interval:</strong>
  <%= @gamble.interval %>
</p>

<p>
  <strong>Good outcome:</strong>
  <%= @gamble.good_outcome %>
</p>

<p>
  <strong>Bad outcome:</strong>
  <%= @gamble.bad_outcome %>
</p>

<%= link_to 'Edit', edit_gamble_path(@gamble) %> |
<%= link_to 'Back', gambles_path %>