config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :survey_instances
  resources :gamble_results
  
  resources :gambles do
    member do
      get 'run'
      
    end
  end
  
  resources :surveys

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signin'  => 'users#new'
  get 'gamble'  => 'static_pages#gamble'
  get 'vas'     => 'static_pages#vas'
  

  
  

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :user
  
  has_many :sections
  accepts_nested_attributes_for :sections, allow_destroy: true
  
  validates :title, :description, :instructions, presence: true
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @survey = Survey.find(params[:id])
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:title, :description, :instructions, 
                                    sections_attributes: [ :id, :title, :description, :instructions, :_destroy,
                                    gambles_attributes: [:id, :title, :description, :instructions, :interval, :good_outcome, :bad_outcome, :_destroy],
                                    questions_attributes: [ :id, :content, :_destroy, 
                                    options_attributes: [ :id, :content, :_destroy ] ] ],
                                    survey_instances_attributes: [ :id, :answer_id, :gamble_result_id, :patient_id ] )
    end                                  
                                      
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <h1>Survey</h1>
  
  <div class="form-group">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>  
  
  <div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :instructions, "Instructions" %>
    <%= f.text_area :instructions, class: 'form-control' %>
  </div>

  <%= f.fields_for :sections do |builder| %>
    <%= render 'section_fields', f: builder %>
  <% end %>  

  <%= link_to_add_fields "Add Section", f, :sections %>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/surveys/_gamble_fields.html.erb
<fieldset>
  <h2>Gamble</h2>
  <%= f.hidden_field :_destroy %>
  <%= link_to "Remove", '#', class: "remove_fields pull-right" %>
   <div class="form-group row">
    <div class="col-sm-2 form-control-label">
      <%= f.label :title, "Title" %>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control' %><br>
    </div>
    <div class="col-sm-2 form-control-label">
      <%= f.label :description, "Description" %>
    </div>
    <div class="col-sm-10">
      <%= f.text_area :description, class: 'form-control' %><br>
    </div>
    <div class="col-sm-2 form-control-label">
      <%= f.label :instructions, "Instructions" %>
    </div>
    <div class="col-sm-10">
      <%= f.text_area :instructions, class: 'form-control' %><br>
    </div>
    <div class="col-sm-2" >
      <%= f.label :good_outcome, "Good Outcome" %>
    </div>
    <div class="col-sm-10">
      <%= f.text_area :good_outcome, class: 'form-control' %><br>
    </div>
    <div class="col-sm-2" >
      <%= f.label :bad_outcome, "Bad Outcome" %>
    </div>
    <div class="col-sm-10">
      <%= f.text_area :bad_outcome, class: 'form-control' %><br>
    </div>
</fieldset>

app/views/surveys/_option_fields.html.erb
<fieldset>
  <h4>Option</h4>
  <div class="form-group row">
    <div class="col-sm-2 form-control-label">
      <%= f.label :content, "Content" %>  
    </div>
    <div class="col-sm-10">
      <%= f.text_field :content, class: 'form-control' %><br>
    </div>
    <%= f.hidden_field :_destroy %>
    <%= link_to "Remove", '#', class: "remove_fields" %>
  </div>
  
</fieldset>

app/views/surveys/_question_fields.html.erb
<fieldset>
  <h3>Question</h3>
  <div class="form-group row">
    <div class="col-sm-2 form-control-label">
      <%= f.label :content, "Content" %>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :content, class: 'form-control' %><br>
    </div>
    <%= f.hidden_field :_destroy %>
    <%= link_to "Remove", '#', class: "remove_fields" %>
  </div>
  
  <%= f.fields_for :options do |builder| %>
    <%= render 'option_fields', f: builder %>
  <% end %>

  <%= link_to_add_fields "Add Option", f, :options %>
</fieldset>

app/views/surveys/_section_fields.html.erb
<fieldset>
  <h2>Section</h2>
  <%= f.hidden_field :_destroy %>
  <%= link_to "Remove", '#', class: "remove_fields pull-right" %>
  <div class="form-group row">
    <div class="col-sm-2 form-control-label">
      <%= f.label :title, "Title" %>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control' %><br>
    </div>
    <div class="col-sm-2 form-control-label">
      <%= f.label :description, "Description" %>
    </div>
    <div class="col-sm-10">
      <%= f.text_area :description, class: 'form-control' %><br>
    </div>
    <div class="col-sm-2 form-control-label">
      <%= f.label :instructions, "Instructions" %>
    </div>
    <div class="col-sm-10">
      <%= f.text_area :instructions, class: 'form-control' %><br>
    </div>
  </div>
  
  <%= f.fields_for :gambles do |builder| %>
    <%= render 'gamble_fields', f: builder %>
  <% end %> 
  
  <%= f.fields_for :questions do |builder| %>
    <%= render 'question_fields', f: builder %>
  <% end %>
  
  <%= link_to_add_fields "Add Gamble", f, :gambles %>
  <%= link_to_add_fields "Add Question", f, :questions %>
  
</fieldset>

app/views/surveys/_vas.html.erb
<div id="vas" class="container">
  <input id="ex1" data-slider-id='ex1Slider' type="text" data-slider-min="0" data-slider-max="10" data-slider-step="1" data-slider-value="5"/>  
</div>

<script>
  
  $('#ex1').slider({
  	formatter: function(value) {
  		return 'Current value: ' + value;
  	}
  });
  
</script>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Surveys</h1>

<table class="table table-striped table-hover">
  <thead class="thead-inverse">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Start</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= link_to survey.title, survey %></td>
        <td><%= link_to survey.description, survey %></td>
        <td><%= link_to 'Start', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Delete', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path, class: "btn btn-primary" %>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
        <% @survey.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="container survey_container">
    <div class="survey_header">
      <h1><%= @survey.title %> </h1>
      <p><%= @survey.description %></p>
      <p><%= @survey.instructions %></p>
    </div>
    
    <ol class="sections">
      <% @survey.sections.each do |section| %>
        <li>
          <h3><%= section.title %></h3>
          <p><%= section.description %></p>
          <p><%= section.instructions %></p>
          <% section.gambles.each do |gamble| %>
            <%= render 'gambles/run', gamble: gamble %>
          <% end %>
          
          <ol class="questions">
            <% section.questions.each do |question| %>
              <li><%= question.content %></li>
            <% end %>  
          </ol>
          
        </li>
      <% end %>    
    </ol>
    
  
  </div>
  
  <%= link_to 'Back', surveys_path %>  

<% end %>