config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :survey_instances
  resources :gamble_results
  
  resources :gambles do
    member do
      get 'run'
      
    end
  end
  
  resources :surveys

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signin'  => 'users#new'
  get 'gamble'  => 'static_pages#gamble'
  get 'vas'     => 'static_pages#vas'
  

  
  

end

app/models/gamble_result.rb
class GambleResult < ActiveRecord::Base
end

app/controllers/gamble_results_controller.rb
class GambleResultsController < ApplicationController
  before_action :set_gamble_result, only: [:show, :edit, :update, :destroy]

  # GET /gamble_results
  # GET /gamble_results.json
  def index
    @gamble_results = GambleResult.all
  end

  # GET /gamble_results/1
  # GET /gamble_results/1.json
  def show
  end

  # GET /gamble_results/new
  def new
    @gamble_result = GambleResult.new
  end

  # GET /gamble_results/1/edit
  def edit
  end

  # POST /gamble_results
  # POST /gamble_results.json
  def create
    
    # raise params.to_s
    # {"final_good_outcome_percent"=>"100", "gamble_id"=>"1", "controller"=>"gamble_results", "action"=>"create", "format"=>"json"}
    @gamble_result = GambleResult.new
    @gamble_result.final_good_outcome_percent = params['final_good_outcome_percent']
    @gamble_result.gamble_id = params['gamble_id']
    @gamble_result.survey_instance_id = params['survey_instance_id'].to_i
    # raise @gamble_result.to_s
    
    respond_to do |format|
      if @gamble_result.save
        format.html { redirect_to @gamble_result, notice: 'Gamble result was successfully created.' }
        format.json { render :show, status: :created, location: @gamble_result }
      else
        format.html { render :new }
        format.json { render json: @gamble_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gamble_results/1
  # PATCH/PUT /gamble_results/1.json
  def update
    respond_to do |format|
      if @gamble_result.update(gamble_result_params)
        format.html { redirect_to @gamble_result, notice: 'Gamble result was successfully updated.' }
        format.json { render :show, status: :ok, location: @gamble_result }
      else
        format.html { render :edit }
        format.json { render json: @gamble_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gamble_results/1
  # DELETE /gamble_results/1.json
  def destroy
    @gamble_result.destroy
    respond_to do |format|
      format.html { redirect_to gamble_results_url, notice: 'Gamble result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gamble_result
      @gamble_result = GambleResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gamble_result_params
      params.require(:gamble_result).permit('final_good_outcome_percent', 'gamble_id')
    end
end

app/helpers/gamble_results_helper.rb
module GambleResultsHelper
end

app/views/gamble_results/_form.html.erb
<%= form_for(@gamble_result) do |f| %>
  <% if @gamble_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gamble_result.errors.count, "error") %> prohibited this gamble_result from being saved:</h2>

      <ul>
      <% @gamble_result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :final_good_outcome_percent %><br>
    <%= f.number_field :final_good_outcome_percent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gamble_results/edit.html.erb
<h1>Editing Gamble Result</h1>

<%= render 'form' %>

<%= link_to 'Show', @gamble_result %> |
<%= link_to 'Back', gamble_results_path %>

app/views/gamble_results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gamble Results</h1>

<table>
  <thead>
    <tr>
      <th>Final good outcome percent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gamble_results.each do |gamble_result| %>
      <tr>
        <td><%= gamble_result.final_good_outcome_percent %></td>
        <td><%= link_to 'Show', gamble_result %></td>
        <td><%= link_to 'Edit', edit_gamble_result_path(gamble_result) %></td>
        <td><%= link_to 'Destroy', gamble_result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gamble result', new_gamble_result_path %>

app/views/gamble_results/new.html.erb
<h1>New Gamble Result</h1>

<%= render 'form' %>

<%= link_to 'Back', gamble_results_path %>

app/views/gamble_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Final good outcome percent:</strong>
  <%= @gamble_result.final_good_outcome_percent %>
</p>

<%= link_to 'Edit', edit_gamble_result_path(@gamble_result) %> |
<%= link_to 'Back', gamble_results_path %>