config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :survey_instances
  resources :gamble_results
  
  resources :gambles do
    member do
      get 'run'
      
    end
  end
  
  resources :surveys

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signin'  => 'users#new'
  get 'gamble'  => 'static_pages#gamble'
  get 'vas'     => 'static_pages#vas'
  

  
  

end

app/models/survey_instance.rb
class SurveyInstance < ActiveRecord::Base
  belongs_to :survey
  belongs_to :patient
  
  def took_gamble(gamble_id)
    GambleResult.where(survey_instance_id: self.id.to_s, gamble_id: gamble_id).length > 0
  end
  
end

app/controllers/survey_instances_controller.rb
class SurveyInstancesController < ApplicationController
  before_action :set_survey_instance, only: [:show, :edit, :update, :destroy]

  # GET /survey_instances
  # GET /survey_instances.json
  def index
    @survey_instances = SurveyInstance.all
  end

  # GET /survey_instances/1
  # GET /survey_instances/1.json
  def show
    @section_id = params[:section].to_i || 0
    # raise @section_id.to_s
    @survey = @survey_instance.survey
    
  end

  # GET /survey_instances/new
  def new
    @survey_instance = SurveyInstance.new
  end

  # GET /survey_instances/1/edit
  def edit
  end

  # POST /survey_instances
  # POST /survey_instances.json
  def create
    @survey_instance = SurveyInstance.new(survey_instance_params)

    respond_to do |format|
      if @survey_instance.save
        format.html { redirect_to @survey_instance, notice: 'Survey instance was successfully created.' }
        format.json { render :show, status: :created, location: @survey_instance }
      else
        format.html { render :new }
        format.json { render json: @survey_instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /survey_instances/1
  # PATCH/PUT /survey_instances/1.json
  def update
    respond_to do |format|
      if @survey_instance.update(survey_instance_params)
        format.html { redirect_to @survey_instance, notice: 'Survey instance was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey_instance }
      else
        format.html { render :edit }
        format.json { render json: @survey_instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survey_instances/1
  # DELETE /survey_instances/1.json
  def destroy
    @survey_instance.destroy
    respond_to do |format|
      format.html { redirect_to survey_instances_url, notice: 'Survey instance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey_instance
      @survey_instance = SurveyInstance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_instance_params
      params.require(:survey_instance).permit(:patient_id, :survey_id)
    end
end

app/helpers/survey_instances_helper.rb
module SurveyInstancesHelper
end

app/views/survey_instances/_form.html.erb
<%= form_for(@survey_instance) do |f| %>
  <% if @survey_instance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey_instance.errors.count, "error") %> prohibited this survey_instance from being saved:</h2>

      <ul>
      <% @survey_instance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.text_field :patient_id %>
  </div>
  <div class="field">
    <%= f.label :survey_id %><br>
    <%= f.text_field :survey_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/survey_instances/edit.html.erb
<h1>Editing Survey Instance</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey_instance %> |
<%= link_to 'Back', survey_instances_path %>

app/views/survey_instances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Survey Instances</h1>

<table>
  <thead>
    <tr>
      <th>Patient</th>
      <th>Survey</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @survey_instances.each do |survey_instance| %>
      <tr>
        <td><%= survey_instance.patient_id %></td>
        <td><%= survey_instance.survey_id %></td>
        <td><%= link_to 'Show', survey_instance %></td>
        <td><%= link_to 'Edit', edit_survey_instance_path(survey_instance) %></td>
        <td><%= link_to 'Destroy', survey_instance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey instance', new_survey_instance_path %>

app/views/survey_instances/new.html.erb
<h1>New Survey Instance</h1>

<%= render 'form' %>

<%= link_to 'Back', survey_instances_path %>

app/views/survey_instances/show.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
        <% @survey.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="container survey_container">
    <br>
    <h2> <%= @survey_instance.patient_id %></h2>
    <hr>
    
    <div class="survey_header">
      <h1><%= @survey.title %> </h1>
      <p><%= @survey.description %></p>
      <p><%= @survey.instructions %></p>
    </div>
    
    <ol class="sections">
      <% section = @survey.sections[@section_id] %>
        <li>
          <h3>
            <span>Section Title: </span>
            <%= section.title %>
          </h3>
          <p><%= section.description %></p>
          <p><%= section.instructions %></p>
          <% section.gambles.each do |gamble| %>
          <% if !@survey_instance.took_gamble(gamble.id) %>
            <%= render 'gambles/run_gamble', gamble: gamble %>
            <br>
            <br>
            <h4>On a scale of 1-10, how much pain to you feel?</h4>
            <br>
          <% end %>
          <% end %>
          
          <ol class="questions">
            <% section.questions.each do |question| %>
              <li><%= question.content %></li>
            <% end %>  
          </ol>
          
        </li>
    </ol>
    
  
  </div>
  <br>
  <br>
  <% if @survey.sections[@section_id - 1] && @section_id != 0 %> 
    <%= link_to 'Back', survey_instance_path(@survey_instance, section: (@section_id - 1))%>
  <% end %> 
  <% if (@survey.sections[@section_id + 1]) %>
    <%= link_to 'Next', survey_instance_path(@survey_instance, section: (@section_id + 1))%> 
  <% end %>

<% end %>